// YouTube Subtitle Extractor
// Uses YouTube's player API (via main world injection) to get captions + PO Token

export interface SubtitleSegment {
  startMs: number;
  durationMs: number;
  text: string;
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
  vssId?: string;
}

interface PlayerAPIData {
  captionTracks: CaptionTrack[];
  audioCaptionTracks: { url: string; vssId: string; languageCode?: string; kind?: string }[];
  clientVersion: string;
  device: Record<string, string> | null;
}

const LOG = '[Eniwer YT字幕]';

export class YouTubeSubtitleExtractor {
  private captionTracks: CaptionTrack[] = [];
  private navigationHandler: (() => void) | null = null;
  private onVideoChange: ((videoId: string) => void) | null = null;
  private currentVideoId: string | null = null;

  static isYouTubePage(): boolean {
    return window.location.hostname === 'www.youtube.com' && window.location.pathname === '/watch';
  }

  static getVideoId(): string | null {
    const params = new URLSearchParams(window.location.search);
    return params.get('v');
  }

  setOnVideoChange(callback: (videoId: string) => void): void {
    this.onVideoChange = callback;
  }

  init(): void {
    this.listenForNavigation();
    if (YouTubeSubtitleExtractor.isYouTubePage()) {
      const videoId = YouTubeSubtitleExtractor.getVideoId();
      if (videoId) {
        this.currentVideoId = videoId;
      }
    }
  }

  destroy(): void {
    if (this.navigationHandler) {
      document.removeEventListener('yt-navigate-finish', this.navigationHandler);
      this.navigationHandler = null;
    }
    this.captionTracks = [];
    this.currentVideoId = null;
  }

  private listenForNavigation(): void {
    this.navigationHandler = () => {
      if (YouTubeSubtitleExtractor.isYouTubePage()) {
        const videoId = YouTubeSubtitleExtractor.getVideoId();
        if (videoId && videoId !== this.currentVideoId) {
          this.currentVideoId = videoId;
          this.captionTracks = [];
          this.onVideoChange?.(videoId);
        }
      }
    };
    document.addEventListener('yt-navigate-finish', this.navigationHandler);
  }

  /**
   * Extract player data via background's chrome.scripting.executeScript (MAIN world).
   * This bypasses YouTube's CSP which blocks inline script injection.
   */
  async extractViaPlayerAPI(): Promise<PlayerAPIData | null> {
    for (let attempt = 0; attempt < 10; attempt++) {
      try {
        const response = await chrome.runtime.sendMessage({
          type: 'EXTRACT_YT_PLAYER_DATA',
        });

        console.log(LOG, `  主世界注入 attempt=${attempt}`, 'success=', response.success,
          'data=', response.data ? `captionTracks=${response.data.captionTracks?.length}` : 'null',
          'debug=', response.data?._debug || response.error || '');

        if (response.success && response.data?.captionTracks?.length > 0) {
          return response.data;
        }
      } catch (e) {
        console.warn(LOG, `  主世界注入 attempt=${attempt} 异常:`, e);
      }

      await new Promise(r => setTimeout(r, 800));
    }
    return null;
  }

  /**
   * Extract PO token from audio caption tracks or cached timedtext URL.
   */
  extractPotToken(
    selectedTrack: CaptionTrack,
    audioTracks: { url: string; vssId: string; languageCode?: string; kind?: string }[]
  ): { pot: string | null; potc: string | null } {
    // Try to find matching audio track by vssId
    let matched = audioTracks.find(t => t.vssId === selectedTrack.vssId);

    // Fallback: match by languageCode + kind
    if (!matched && selectedTrack.languageCode) {
      const kind = selectedTrack.isAutoGenerated ? 'asr' : '';
      matched = audioTracks.find(t =>
        t.languageCode === selectedTrack.languageCode && (t.kind || '') === kind
      );
    }

    // Fallback: match by languageCode only
    if (!matched && selectedTrack.languageCode) {
      matched = audioTracks.find(t => t.languageCode === selectedTrack.languageCode);
    }

    // Fallback: first available
    if (!matched && audioTracks.length > 0) {
      matched = audioTracks[0];
    }

    if (matched?.url) {
      try {
        const url = new URL(matched.url);
        const pot = url.searchParams.get('pot');
        const potc = url.searchParams.get('potc');
        if (pot) return { pot, potc };
      } catch { /* ignore */ }
    }

    return { pot: null, potc: null };
  }

  /**
   * Build the full timedtext URL with PO token and device params.
   */
  buildSubtitleUrl(
    track: CaptionTrack,
    potToken: { pot: string | null; potc: string | null },
    clientVersion: string,
    device: Record<string, string> | null,
  ): string {
    const url = new URL(track.baseUrl);
    url.searchParams.set('fmt', 'json3');
    url.searchParams.set('xorb', '2');
    url.searchParams.set('xobt', '3');
    url.searchParams.set('xovt', '3');

    if (potToken.pot) {
      url.searchParams.set('pot', potToken.pot);
    }
    if (potToken.potc) {
      url.searchParams.set('potc', potToken.potc);
    }

    if (clientVersion) {
      url.searchParams.set('cver', clientVersion);
    }

    url.searchParams.set('c', 'WEB');
    url.searchParams.set('cplayer', 'UNIPLAYER');

    if (device) {
      if (device.brand) url.searchParams.set('cbrand', device.brand);
      if (device.browserName) url.searchParams.set('cbr', device.browserName);
      if (device.browserVersion) url.searchParams.set('cbrver', device.browserVersion);
      if (device.osName) url.searchParams.set('cos', device.osName);
      if (device.osVersion) url.searchParams.set('cosver', device.osVersion);
      if (device.platform) url.searchParams.set('cplatform', device.platform);
    }

    return url.toString();
  }

  getCaptionTracks(): CaptionTrack[] {
    return this.captionTracks;
  }

  setCaptionTracks(tracks: CaptionTrack[]): void {
    this.captionTracks = tracks;
  }

  selectTrack(preferredLanguage: string): CaptionTrack | null {
    if (this.captionTracks.length === 0) return null;

    if (preferredLanguage !== 'auto') {
      const exact = this.captionTracks.find(t => t.languageCode === preferredLanguage);
      if (exact) return exact;
      const prefix = this.captionTracks.find(t => t.languageCode.startsWith(preferredLanguage.split('-')[0]));
      if (prefix) return prefix;
    }

    const manual = this.captionTracks.find(t => !t.isAutoGenerated);
    return manual || this.captionTracks[0];
  }
}
