// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/plugin-api/plugin-interface.mdx?collection=docs&hash=1774001242998"
import * as docs_5 from "../content/docs/plugin-api/plugin-context.mdx?collection=docs&hash=1774001242998"
import * as docs_4 from "../content/docs/plugin-api/events.mdx?collection=docs&hash=1774001242998"
import * as docs_3 from "../content/docs/plugin-api/capabilities.mdx?collection=docs&hash=1774001242998"
import * as docs_2 from "../content/docs/guides/settings-plugin.mdx?collection=docs&hash=1774001242998"
import * as docs_1 from "../content/docs/guides/getting-started.mdx?collection=docs&hash=1774001242998"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1774001242998"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"guides/getting-started.mdx","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/guides/getting-started.mdx"}, data: docs_1 }, { info: {"path":"guides/settings-plugin.mdx","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/guides/settings-plugin.mdx"}, data: docs_2 }, { info: {"path":"plugin-api/capabilities.mdx","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/plugin-api/capabilities.mdx"}, data: docs_3 }, { info: {"path":"plugin-api/events.mdx","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/plugin-api/events.mdx"}, data: docs_4 }, { info: {"path":"plugin-api/plugin-context.mdx","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/plugin-api/plugin-context.mdx"}, data: docs_5 }, { info: {"path":"plugin-api/plugin-interface.mdx","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/plugin-api/plugin-interface.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/meta.json"},"data":{"title":"Docs","pages":["index","...plugin-api","...guides"]}}, {"info":{"path":"guides/meta.json","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/guides/meta.json"},"data":{"title":"Guides","pages":["getting-started","settings-plugin"]}}, {"info":{"path":"plugin-api/meta.json","absolutePath":"/Users/royzeng/test/eniwer/docs/content/docs/plugin-api/meta.json"},"data":{"title":"Plugin API","pages":["plugin-interface","plugin-context","capabilities","events"]}}])